### PR TITLE
Sort reservations and filter reservations of different dates

### PR DESCRIPTION
**Pull request by aclinal**
Show reservations in ascending order for a better user experience. Also filter
out dates that do not match the selected date.

### CODE REVIEW

**Comment by djensenius** [comment]
Sorry for the long delay on this! I'll be looking at it as soon as I get finished with a big feature. 😄

**Comment by djensenius** [comment]
@aclinal Oops, I don't see the condo brain PR...

**Comment by aclinal** [comment]
@djensenius is there are condo-brain PR required to support this? I think this PR can stand on its own, but certainly can make a condo-brain change if needed

**Review by djensenius — APPROVED** [review]

**Comment by djensenius** [comment]
THANK YOU THANK YOU THANK YOU!!!!!!!!! Merged and (FINALLY) deployed.

**Pull request merged**
